"""A dice simulation
"""
from dice import Die

#Make as number of sided die and roll it ten times

six_sided = Die()
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
six_sided.roll_die(6)
print("\n")
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
six_sided.roll_die(10)
print("\n")
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
six_sided.roll_die(20)
